helm:
  repoURL: ghcr.io/ludat/charts
  chart: herokucito-web
  path: 
  targetRevision: 0.2.0

image:
  repository: ghcr.io/ludat/banana-split
  tag: v0.3.0

preCommand: |
  timeout 10 banana-split migrations init
  banana-split migrations migrate ./migrations

postCommand: |
  if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
    banana-split migrations complete
  fi

expose:
  enabled: true
  host: split.ludat.io

secrets:
  - config

port: 8000

postgres:
  enabled: true
  uriEnv: BANANASPLIT_DATABASE_URL
  ha: true
  backups: true
  failsafe: true

