---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "banana-split.fullname" . }}-migration-start-{{ printf "%s/%s" (include "banana-split.tag" .) (include "banana-split.configChecksum" .) | sha1sum | substr 0 8 }}"
  labels:
    {{- include "banana-split.labels" . | nindent 4 }}
    role: migration-start
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  template:
    metadata:
      name: {{ include "banana-split.fullname" . }}-migration-start
      {{- if .Values.config }}
      annotations:
        {{- include "banana-split.configChecksum" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "banana-split.labels" . | nindent 8 }}
        role: migration-start
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration-start
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ include "banana-split.tag" . }}"
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              set -x
              timeout 10 banana-split migrations init
              banana-split migrations migrate ./migrations

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "banana-split.env" . | nindent 12 }}
          {{- if or .Values.config .Values.envFrom }}
          envFrom:
            {{- if .Values.config }}
            - secretRef:
                name: {{ include "banana-split.fullname" . }}-config
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "banana-split.fullname" . }}-migration-complete
  labels:
    {{- include "banana-split.labels" . | nindent 4 }}
    role: migration-complete
  annotations:
    helm.sh/hook: post-upgrade,post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "banana-split.fullname" . }}-migration-complete
      {{- if .Values.config }}
      annotations:
        {{- include "banana-split.configChecksum" . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "banana-split.labels" . | nindent 8 }}
        role: migration-complete
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration-complete
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ include "banana-split.tag" . }}"
          command:
            - sh
            - -c
            - |
              set -euo pipefail
              set -x
              if ! [[ "$(timeout 10 banana-split migrations status | grep status | sed 's/^ *"status": "\(.*\)"/\1/')" = "Complete" ]]; then
                banana-split migrations complete
              fi

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "banana-split.env" . | nindent 12 }}
          {{- if or .Values.config .Values.envFrom }}
          envFrom:
            {{- if .Values.config }}
            - secretRef:
                name: {{ include "banana-split.fullname" . }}-config
            {{- end }}
            {{- with .Values.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
